#!/bin/ash

if [ "$root" == "" ]; then
	root=/dev/vda
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs none /dev

echo "Mounting $root on /sysroot"
mount $root /sysroot

mount -t 9p -o trans=virtio,ro kvmboot /sysroot/boot
mkdir /sysroot/lib/modules
mount -t tmpfs none /sysroot/lib/modules
tar xvf /sysroot/boot/modules.tgz -C /sysroot/

umount /sysroot/boot

echo $ID > /sysroot/etc/hostname
echo $HOST > /sysroot/etc/kvmhost

if [ -f /sysroot/etc/debian_version ]; then 

cat <<EOF > /sysroot/etc/network/interfaces
auto lo cbr0
iface lo inet loopback

iface cbr0 inet static
        bridge_ports    eth0
        bridge_stp      off
        bridge_maxwait  2
        address 10.0.${IDNUM}.1
        netmask 255.255.0.0
        network 10.0.0.0
        broadcast 10.0.255.255
        gateway 10.0.255.254

        pre-up /sbin/ip link set dev eth0 up
#        up /sbin/ip link set promisc on dev cbr0

source-directory /etc/network/interfaces.d

EOF

elif [ -f /sysroot/etc/redhat-release ]; then

cat <<EOF > /sysroot/etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
IPADDR=10.0.${IDNUM}.1
BROADCAST=10.0.255.255
NETMASK=255.255.0.0
GATEWAY=10.0.255.254
NETWORK=10.0.0.0
BOOTPROTO=none
ONBOOT=yes

EOF

cat <<EOF > /sysroot/etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=no
NOZEROCONF=yes
HOSTNAME=${ID}.${HOST}
EOF

fi

if [ "$init" == "" ]; then
	init=/sbin/init
fi

umount /proc
umount /sys
umount /dev
mount -t proc proc /sysroot/proc
mount -t sysfs sysfs /sysroot/sys
mount -t devtmpfs none /sysroot/dev

exec switch_root -c /dev/console /sysroot $init


