#!/bin/ash

if [ "$root" == "" ]; then
	root=/dev/vda
fi

mount -t proc none /proc
mount -t devtmpfs none /dev

echo "Mounting $root on /sysroot"
mount $root /sysroot

echo $ID > /sysroot/etc/hostname
echo $HOST > /sysroot/etc/kvmhost

if [ -f /sysroot/etc/debian_version ]; then 

cat <<EOF > /sysroot/etc/network/interfaces
auto lo eth0
iface lo inet loopback

iface eth0 inet static
        address 172.16.1.${IDNUM}
        netmask 255.255.255.0
        network 172.16.1.0
        broadcast       172.16.1.255
        gateway 172.16.1.254

source-directory /etc/network/interfaces.d

EOF

elif [ -f /sysroot/etc/redhat-release ]; then

cat <<EOF > /sysroot/etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
IPADDR=172.16.1.${IDNUM}
BROADCAST=172.16.1.255
NETMASK=255.255.255.0
GATEWAY=172.16.1.254
NETWORK=172.16.1.0
BOOTPROTO=none
ONBOOT=yes

EOF

cat <<EOF > /sysroot/etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=no
NOZEROCONF=yes
HOSTNAME=${ID}.${HOST}
EOF

fi

if [ "$init" == "" ]; then
	init=/sbin/init
fi

umount /proc
umount /dev
mount -t proc none /sysroot/proc
mount -t devtmpfs none /sysroot/dev

exec switch_root -c /dev/console /sysroot $init


