#!/bin/ash

if [ "$root" == "" ]; then
	root=/dev/vda
fi

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs none /dev

echo "Mounting $root on /sysroot"
mount $root /sysroot

mount -t 9p -o trans=virtio,ro kvmboot /sysroot/boot
mkdir /sysroot/lib/modules
mount -t tmpfs none /sysroot/lib/modules
tar xvf /sysroot/boot/modules.tgz -C /sysroot/

umount /sysroot/boot

echo $ID > /sysroot/etc/hostname
echo $HOST > /sysroot/etc/kvmhost

if [ -f /sysroot/etc/debian_version ]; then 

cat <<EOF > /sysroot/etc/network/interfaces
auto lo eth0
iface lo inet loopback

iface eth0 inet static
        address 172.16.3.${IDNUM}
        netmask 255.255.255.0
        network 172.16.3.0
        broadcast       172.16.3.255
        gateway 172.16.3.254

source-directory /etc/network/interfaces.d

EOF

elif [ -f /sysroot/etc/redhat-release ]; then

cat <<EOF > /sysroot/etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE=eth0
IPADDR=172.16.3.${IDNUM}
BROADCAST=172.16.3.255
NETMASK=255.255.255.0
GATEWAY=172.16.3.254
NETWORK=172.16.3.0
BOOTPROTO=none
ONBOOT=yes

EOF

cat <<EOF > /sysroot/etc/sysconfig/network
NETWORKING=yes
NETWORKING_IPV6=no
NOZEROCONF=yes
HOSTNAME=${ID}.${HOST}
EOF

fi

if [ "$init" == "" ]; then
	init=/sbin/init
fi

umount /proc
umount /sys
umount /dev
mount -t proc proc /sysroot/proc
mount -t sysfs sysfs /sysroot/sys
mount -t devtmpfs none /sysroot/dev

exec switch_root -c /dev/console /sysroot $init


